title: Lovely Docs
description: Documention, coming soon
theme: just-the-docs
color_scheme: dark

url: https://docs.lsr.gg

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
